[package]
name = "cl0"
version = "0.1.0"
edition = "2024"

[dependencies]
cl0_parser = { path = "./crates/cl0_parser" }

[workspace]
members = [
    "crates/cl0_parser",
    "crates/cl0_node",
    "."]
    
[[bin]]
name = "cl0_parser"
path = "src/main.rs"
